---
- hosts: 127.0.0.1
  connection: local
  become: True
  vars:
    install_discord: True
    primary_user: gazay
    primary_user_group: gazay
  roles:
    - { role: common, tags: common }
    - { role: browser, tags: browser }
    - { role: terminal, tags: terminal }
    - { role: communication, tags: communication }
    - { role: development, tags: development }
#   - { role: entertainment, tags: entertainment }
#   - { role: writing, tags: writing }
