---
- hosts: 127.0.0.1
  connection: local
  become: True
  vars:
    primary_user: gazay
    primary_user_group: gazay
  roles:
    - { role: common, tags: common }
    - { role: terminal, tags: terminal }
    - { role: development, tags: development }
