---
- name: install OS pkg dependencies
  become: yes
  become_user: root
  with_items: '{{ anaconda_dep_pkgs | default([]) }}'
  loop_control:
    loop_var: anaconda_os_pkg
  package:
    state: present
    name: '{{ anaconda_os_pkg }}'

- name: check for installation of Anaconda
  become: yes
  stat:
    path: '{{ anaconda_install_dir }}/bin/conda'
  changed_when: false
  register: anaconda_conda_binary

- when: not anaconda_conda_binary.stat.exists
  block:
    - name: download installer...
      become: yes
      become_user: root
      get_url:
        url: "https://repo.anaconda.com/archive/{{ anaconda_installer }}"
        dest: "/tmp/{{ anaconda_installer }}"
        timeout: 600
        mode: 0755

    - name: install...
      become: yes
      become_user: root
      command: "bash /tmp/{{ anaconda_installer }} -b -p {{ anaconda_install_dir }}"
      args:
        creates: anaconda_install_dir

  always:
    - name: delete installer...
      become: yes
      become_user: root
      file:
        path: /tmp/{{ anaconda_installer }}
        state: absent

- name: link anaconda...
  become: yes
  become_user: root
  file:
    src: '{{anaconda_install_dir}}'
    dest: '{{anaconda_link_dir}}'
    state: link

- name: update conda pkgs...
  become: yes
  become_user: root
  command: '{{anaconda_link_dir}}/bin/conda update -y --all'
