---
- name: "Create directories for ruby tools"
  file:
    path: "/tmp/{{ item }}"
    state: directory
  with_items: [ruby-install, chruby]

- name: Check for ruby-install
  become_user: "{{ primary_user }}"
  shell: command -v ruby-install
  ignore_errors: True
  register: ruby_install

- name: Unarchive ruby-install
  unarchive:
    remote_src: True
    src: https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz
    dest: /tmp
  when: ruby_install is failed

- name: Install ruby-install
  shell: make install chdir=/tmp/ruby-install-0.7.0
  when: ruby_install is failed

- name: Check for chruby
  become_user: "{{ primary_user }}"
  shell: command -v chruby-exec
  ignore_errors: True
  register: chruby

- name: Unarchive chruby
  unarchive:
    remote_src: True
    src: https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
    dest: /tmp
  when: chruby is failed

- name: Install chruby
  shell: make install chdir=/tmp/chruby-0.3.9
  when: chruby is failed

- name: Check for ruby
  stat:
    path: "/home/{{ primary_user }}/.rubies/ruby-2.5.3"
  register: ruby

- name: Install latest ruby
  become_user: "{{ primary_user }}"
  shell: ruby-install ruby 2.5
  when: not ruby.stat.exists

- name: Deploy chruby autoload script
  copy: src=/usr/local/share/chruby/chruby.sh
        dest=/etc/profile.d/chruby.sh

- name: Install bundler
  become_user: "{{ primary_user }}"
  shell: chruby-exec 2.5 && gem install bundler
