---
- name: Install terminator
  apt:
    name: terminator
    state: latest
    update_cache: True

- name: Ensure terminator config directory exist
  file:
    path: "/home/{{ primary_user }}/.config/terminator"
    state: directory
    owner: "{{ primary_user }}"
    group: "{{ primary_user_group }}"

- name: Check terminator config exists
  stat:
    path: "/home/{{ primary_user }}/.config/terminator/config"
  register: tcfg

- name: Create terminator config
  template:
    src: config
    dest: "/home/{{ primary_user }}/.config/terminator/config"
    owner: "{{ primary_user }}"
    group: "{{ primary_user_group }}"
  when: not tcfg.stat.exists
