---
- name: Update and upgrade the apt
  apt:
    update_cache: True
    upgrade: True

- name: Install common stuff
  apt:
    name: "{{ common_packages }}"
    state: present

- name: Remove excess packages
  apt:
    name: "{{ excess_packages }}"
    state: absent

- name: Check for keepassxc
  become_user: "{{ primary_user }}"
  shell: command -v keepassxc
  ignore_errors: True
  register: keepassxc

- name: Install KeePassXC
  shell: snap install keepassxc
  when: keepassxc is failed

- name: Install fonts
  import_tasks: fonts.yml

- name: Dropbox installation
  import_tasks: dropbox.yml
  when: install_dropbox

- name: Do SSH tasks
  import_tasks: ssh.yml
